## One-hot-encoding

In [2]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_transformer

In [3]:
df = pd.DataFrame([
    [2,1,'male','A',3],
    [3,2,'female','C',5],
    [3,4,'male','B',7],
    [5,5,'female','A',10],
    [7,5,'female','B',12],
    [2,5,'male','A',7],
    [9,2,'male','C',13]
], columns=['hours', 'attendance', 'gender', 'cate', 'score'])
df

hours  attendance  gender cate  score
0      2           1    male    A      3
1      3           2  female    C      5
2      3           4    male    B      7
3      5           5  female    A     10
4      7           5  female    B     12
5      2           5    male    A      7
6      9           2    male    C     13

In [7]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)

ohe.fit(df[['gender']]) # 배열, 2차원 list
print(ohe.transform(df[['gender']]))

[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]


In [8]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder() # Matrix
# ohe = OneHotEncoder(sparse=True)  # Matrix

ohe.fit(df[['gender']])
print(ohe.transform(df[['gender']]))

  (0, 1)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 1)	1.0
  (6, 1)	1.0


In [10]:
ohe = OneHotEncoder(sparse=False)
ohe.fit(df[['cate']])
print(ohe.transform(df[['cate']]))

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [11]:
import numpy as np
import pandas as pd

df = pd.DataFrame([
    [2,1,'A',3],
    [3,2,'C',5],
    [3,4,'B',7],
    [5,5,'A',10],
    [7,5,'B',12],
    [2,5,'A',7],
    [9,2,'C',13]
], columns=['hours', 'attendance', 'cate', 'score'])

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
ohe.fit(df[['cate']])
print(ohe.transform(df[['cate']]))

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [12]:
df_cate = pd.DataFrame(ohe.transform(df[['cate']]), columns=['cate0', 'cate1', 'cate2'])

print(df_cate)

   cate0  cate1  cate2
0    1.0    0.0    0.0
1    0.0    0.0    1.0
2    0.0    1.0    0.0
3    1.0    0.0    0.0
4    0.0    1.0    0.0
5    1.0    0.0    0.0
6    0.0    0.0    1.0


In [13]:
df = pd.concat([df[['hours', 'attendance']], df_cate, df[['score']]], axis=1)
print(df)

   hours  attendance  cate0  cate1  cate2  score
0      2           1    1.0    0.0    0.0      3
1      3           2    0.0    0.0    1.0      5
2      3           4    0.0    1.0    0.0      7
3      5           5    1.0    0.0    0.0     10
4      7           5    0.0    1.0    0.0     12
5      2           5    1.0    0.0    0.0      7
6      9           2    0.0    0.0    1.0     13


In [14]:
x_data = df[['hours', 'attendance', 'cate0', 'cate1', 'cate2']]
y_data = df['score']
print(x_data)
print(y_data)

   hours  attendance  cate0  cate1  cate2
0      2           1    1.0    0.0    0.0
1      3           2    0.0    0.0    1.0
2      3           4    0.0    1.0    0.0
3      5           5    1.0    0.0    0.0
4      7           5    0.0    1.0    0.0
5      2           5    1.0    0.0    0.0
6      9           2    0.0    0.0    1.0
0     3
1     5
2     7
3    10
4    12
5     7
6    13
Name: score, dtype: int64
