## 빙어 낚시터를 방문시 잡을 수 있는 물고기의 예상 크기는?

In [1]:
import numpy as np

In [54]:
# 가상의 데이터를 만들기위하여 도메인 조사
fish = np.arange(6, 11)
print(type(fish))
print(fish.shape)
print(fish)

<class 'numpy.ndarray'>
(5,)
[ 6  7  8  9 10]


In [55]:
tot = np.sum(fish)
print(tot)

40


In [56]:
mean = np.mean(fish)
print(mean)

8.0


In [58]:
np.random.seed(1)
fish = np.random.randint(6, 11, size=100)  # 빙어 100 마리 
print(type(fish))
print(fish)

<class 'numpy.ndarray'>
[ 9 10  6  7  9  6  6  7 10 10  7  8 10  8 10  9 10  8 10  8 10  7  7  6
  7  7  7  7  6 10  7  6  6  9  8  7  6  9  7  7  9 10  6  7  9 10  8 10
  6  9  7  8  6 10  7  8  8  7  6  7  9 10  9  7  9  6  6  8  8  7  9 10
  8  6  6  7  7  9  6  6 10  8 10  9  9  6  9 10  9 10 10 10  7  6 10  8
  6  8 10  7]


In [59]:
tot = np.sum(fish)
print(tot)

797


In [60]:
mean = np.mean(fish)
print(mean)

7.97


In [61]:
print('예상되는 물고기의 크기:', mean, 'cm')
print('기대되는 물고기의 크기:', mean, 'cm') # 기대값 = 보통 = 평균
print('대표적으로 많이 잡히는 물고기의 크기:', mean, 'cm')

예상되는 물고기의 크기: 7.97 cm
기대되는 물고기의 크기: 7.97 cm
대표적으로 많이 잡히는 물고기의 크기: 7.97 cm


In [62]:
# 7.97 cm의 물고기만 잡히는 않음, 편차: 평균으로부터의 차이
for item in fish[0:10]:
    print(mean-item) # 개별 항목에 대한 편차, 편차 = 평균 - 데이터

-1.0300000000000002
-2.0300000000000002
1.9699999999999998
0.9699999999999998
-1.0300000000000002
1.9699999999999998
1.9699999999999998
0.9699999999999998
-2.0300000000000002
-2.0300000000000002


In [11]:
# 평균으로부터의 차이(편차)는 0이 나와야 정확히 빙어의 크기를 예측 가능하다.
# 편차가 작아야 기대값이 정확하다.

In [65]:
# 100마리를 잡은 사람이 평균 7.97 cm라고하는데 모든 차이를 알고싶다.
fish_devi = 0; # 편차의 합
for item in fish:  
    fish_devi = fish_devi + (mean-item) # 개별 항목에 대한 편차의 누적 합
    
print('편차의 합: {0:.1f}'.format(fish_devi))    
# 100마리의 빙어는 모두 7.97 cm로 편차가 없다. 논리적 에러

편차의 합: -0.0


In [66]:
# 편차의 합은 왜 0?
src = np.arange(-2, 6)
src

array([-2, -1,  0,  1,  2,  3,  4,  5])

In [67]:
m = np.mean(src)
print('mean:', m)
for item in src:
    print(m-item)

mean: 1.5
3.5
2.5
1.5
0.5
-0.5
-1.5
-2.5
-3.5


In [68]:
hap = 0
for item in src:
    hap = hap + (m-item)
    
print('편차의 합:', hap)    

편차의 합: 0.0


In [16]:
# 100마리의 빙어는 모두 7.97 cm로 편차가 없다.
# 편차가 존재하는데 편차가 없다는 논리적 모순에 빠짐.

In [70]:
# 편차의 부호를 변경(제곱)하여 모두 더함.
fish_devi = 0  # 편차
fish_devi_square = 0; # 편차의 합
for item in fish:
    fish_devi = mean - item
    fish_devi_square = fish_devi_square + (fish_devi ** 2)

print('평균:', mean)    
print('편차의 합: {0:.1f}'.format(fish_devi_square)) 

평균: 7.97
편차의 합: 216.9


In [72]:
# 평균 편차를 알고 싶음, 분산, 2.191 cm
var = fish_devi_square / (100-1) # 표본분산 
# 분산: 데이터들이 평균(대표값)으로부터 얼마나 떨어져 있는지의 척도
var

2.191010101010102

In [19]:
# 인하대학교 앞에 김밥천국 인수시 분산이 너무 큰 경우 발견
# 3월 ~ 6월, 9월 ~ 11월만 장사가 잘됨, 방학때 매출액이 매우 낮음
# 일정하지 않은 매출액으로 운영에 어려움이 많아 인수 포기.

In [73]:
# 분산은 음수를 양수로 변경하기위해 편차를 제곱했음으로 실제 편차가 아님.
print(np.sqrt(4))
print(np.sqrt(9))
print(np.sqrt(16))
print(np.sqrt(10))
sd = np.sqrt(var)
print(sd) # 빙어 잡을시 상황에따라 약 1.4802 cm의 차이가 존재할수 있음.

2.0
3.0
4.0
3.1622776601683795
1.4802061008555876


In [74]:
print('평균:', mean)    # 실제 편차가 제곱되어 있음
print('분산:', var)    # 실제 편차가 제곱되어 있음
print('표준편차:', sd) # 제곱을 해제함.
print('예상 빙어의 크기:', mean-sd,' ~',mean+sd)

평균: 7.97
분산: 2.191010101010102
표준편차: 1.4802061008555876
예상 빙어의 크기: 6.489793899144412  ~ 9.450206100855587


In [75]:
fish

array([ 9, 10,  6,  7,  9,  6,  6,  7, 10, 10,  7,  8, 10,  8, 10,  9, 10,
        8, 10,  8, 10,  7,  7,  6,  7,  7,  7,  7,  6, 10,  7,  6,  6,  9,
        8,  7,  6,  9,  7,  7,  9, 10,  6,  7,  9, 10,  8, 10,  6,  9,  7,
        8,  6, 10,  7,  8,  8,  7,  6,  7,  9, 10,  9,  7,  9,  6,  6,  8,
        8,  7,  9, 10,  8,  6,  6,  7,  7,  9,  6,  6, 10,  8, 10,  9,  9,
        6,  9, 10,  9, 10, 10, 10,  7,  6, 10,  8,  6,  8, 10,  7])

In [76]:
np.var(fish)

2.1691

In [79]:
print(np.std(fish)) # 모표준편차
print(np.std(fish, ddof=1)) # 표본표준편차

1.4727864746798838
1.4802061008555873
