In [1]:
%autosave 0
import warnings
warnings.filterwarnings(action='ignore')

import numpy as np
import pandas as pd

from tensorflow.keras.utils import to_categorical  # one-hot 엔코딩
from sklearn.preprocessing import LabelEncoder     # 명목형 척도 정수화 
from tensorflow.keras.models import load_model     # model 사용

Autosave disabled


In [2]:
model = load_model('./Iris.h5')

In [3]:
df = pd.read_csv('./iris_use.csv', names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"])
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.0          3.5           1.3          0.3  Iris-setosa
1           4.5          2.3           1.3          0.3  Iris-setosa
2           4.4          3.2           1.3          0.2  Iris-setosa
3           5.0          3.5           1.6          0.6  Iris-setosa
4           5.1          3.8           1.9          0.4  Iris-setosa


In [4]:
data = df.values
print(type(data))
print(len(data))
X = data[:, 0:4].astype(float)  # 독립 변수, 정의역
Y_str = data[:, 4]              # 종속 변수, 치역 
print(Y_str)

<class 'numpy.ndarray'>
30
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']


In [15]:
# 문자 레이블을 숫자화, 문자열을 알파벳순으로 그룹화한후 0부터 숫자로 변환
encoder = LabelEncoder()
encoder.fit(Y_str)
Y = encoder.transform(Y_str)
print(Y)

Y_encoded = to_categorical(Y) # one-hot-encoding, 해당 index만 1로 변경
print(Y_encoded[0])
print(Y_encoded[10])
print(Y_encoded[20])

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]


In [17]:
print(encoder.inverse_transform([0, 1, 2])) # Label 확인

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [8]:
# Iris-setosa: 0, Iris-versicolor: 1, Iris-virginica: 2
p = model.predict(X)  # 테스트 데이터 30건
print('p.shape:', p.shape)
print('데이터:', X[0]) # 첫번째 데이터행

p.shape: (30, 3)
데이터: [5.  3.5 1.3 0.3]


In [13]:
# 확률 0 ~ 1사이의 실수값
print('예측값:', p[0]) 
print('예측값: {0:.2f} {1:.2f} {2:.2f}'.format((p[0][0]*100), (p[0][1]*100), (p[0][2]*100))) 
print('LabelEncoder: ', Y[0])
print('One-hot-encoding: ', Y_encoded[0])
print(np.argmax(p[0]))  # 가장 큰값의 index
print(Y_str[0])         # 첫번째 품종

예측값: [0.6113238  0.24229586 0.1463804 ]
예측값: 61.13 24.23 14.64
LabelEncoder:  0
One-hot-encoding:  [1. 0. 0.]
0
Iris-setosa


In [14]:
for item in p: # 2차원 배열에서 1행씩 산출
    print(item)
    print('최대값:', np.max(item), '-> index:', np.argmax(item))
    # 최대값 -> 최대값이 있는 index

[0.6113238  0.24229586 0.1463804 ]
최대값: 0.6113238 -> index: 0
[0.5305852  0.29289085 0.17652385]
최대값: 0.5305852 -> index: 0
[0.59082067 0.25454363 0.15463568]
최대값: 0.59082067 -> index: 0
[0.56073016 0.27176583 0.16750397]
최대값: 0.56073016 -> index: 0
[0.58674175 0.26676133 0.14649695]
최대값: 0.58674175 -> index: 0
[0.5772845  0.26355368 0.15916182]
최대값: 0.5772845 -> index: 0
[0.6297052  0.23762006 0.13267468]
최대값: 0.6297052 -> index: 0
[0.5948652 0.2536923 0.1514425]
최대값: 0.5948652 -> index: 0
[0.6348448  0.23341754 0.13173766]
최대값: 0.6348448 -> index: 0
[0.61214805 0.24476682 0.14308515]
최대값: 0.61214805 -> index: 0
[0.22142059 0.46498328 0.31359613]
최대값: 0.46498328 -> index: 1
[0.21214917 0.45129567 0.33655518]
최대값: 0.45129567 -> index: 1
[0.18839653 0.4615827  0.3500209 ]
최대값: 0.4615827 -> index: 1
[0.19086258 0.42990875 0.37922874]
최대값: 0.42990875 -> index: 1
[0.18264143 0.44901896 0.36833966]
최대값: 0.44901896 -> index: 1
[0.1934684  0.4327364  0.37379518]
최대값: 0.4327364 -> index: 1
[0.

In [18]:
# softmax 함수의 값이 1이되는지 확인
# 컴퓨터는 내부적으로 정수 연산이라 미세한 오차 발생
for item in p:
    print(item, ' 합계: {0:0.0f}'.format(np.sum(item)))

[0.6113238  0.24229586 0.1463804 ]  합계: 1
[0.5305852  0.29289085 0.17652385]  합계: 1
[0.59082067 0.25454363 0.15463568]  합계: 1
[0.56073016 0.27176583 0.16750397]  합계: 1
[0.58674175 0.26676133 0.14649695]  합계: 1
[0.5772845  0.26355368 0.15916182]  합계: 1
[0.6297052  0.23762006 0.13267468]  합계: 1
[0.5948652 0.2536923 0.1514425]  합계: 1
[0.6348448  0.23341754 0.13173766]  합계: 1
[0.61214805 0.24476682 0.14308515]  합계: 1
[0.22142059 0.46498328 0.31359613]  합계: 1
[0.21214917 0.45129567 0.33655518]  합계: 1
[0.18839653 0.4615827  0.3500209 ]  합계: 1
[0.19086258 0.42990875 0.37922874]  합계: 1
[0.18264143 0.44901896 0.36833966]  합계: 1
[0.1934684  0.4327364  0.37379518]  합계: 1
[0.19446263 0.43891472 0.36662266]  합계: 1
[0.26893538 0.42812988 0.30293474]  합계: 1
[0.21007816 0.46154332 0.32837853]  합계: 1
[0.20772721 0.41872522 0.37354752]  합계: 1
[0.07539678 0.2957611  0.6288421 ]  합계: 1
[0.11242773 0.35726553 0.5303067 ]  합계: 1
[0.09401267 0.374579   0.53140837]  합계: 1
[0.11294377 0.37683454 0.51022166]  합

In [19]:
# Iris-setosa: 0, Iris-versicolor: 1, Iris-virginica: 2
def decode(data):  # data: 1차원 배열, predict는 2차원 배열을 리턴함
    index = np.argmax(data) # 최대값의 index를 찾아줌
    if index == 0:
        label = 'Iris-setosa'
    elif index == 1:
        label = 'Iris-versicolor'
    elif index == 2:
        label = 'Iris-virginica'
        
    return label

In [20]:
print(len(p))
for i in range(len(p)):
    print('Target(실제값):', Y_str[i], ' Y hat(예측값):', decode(p[i]))

30
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-setosa  Y hat(예측값): Iris-setosa
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y hat(예측값): Iris-versicolor
Target(실제값): Iris-versicolor  Y h

In [21]:
# input 함수의 사용
# 5.1,3.5,1.4,0.2
src = input('꽃받침 길이, 꽃받침 넓이, 꽃잎 길이, 꽃잎 넓이를 입력하세요.')
print(type(src))
print(src)

꽃받침 길이, 꽃받침 넓이, 꽃잎 길이, 꽃잎 넓이를 입력하세요.5.1,3.5,1.4,0.2
<class 'str'>
5.1,3.5,1.4,0.2


In [22]:
data = np.array(src.split(','), dtype=float) # 1차원 텐서
print(data.shape)
print(data)

(4,)
[5.1 3.5 1.4 0.2]


In [23]:
X = np.array([data])  # 2차원 텐서(배열)로 변환
print(X.shape)
print(X)
p = model.predict(X)  # 2차원 배열 대입
print('p:', p)

for i in range(len(p)):
    print('예측값:', decode(p[i])) # [[0.9129314  0.0839827  0.00308592]]

(1, 4)
[[5.1 3.5 1.4 0.2]]
p: [[0.6227249  0.23900543 0.13826972]]
예측값: Iris-setosa
